language: ruby
cache: bundler
rvm:
  - 2.1.1
  - 2.0.0
  - 1.9.3
  - rbx-2
  - ruby-head
  - jruby-head
before_install:
  - bundle init
  - echo 'gemspec' >> Gemfile
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
